# Generated by Django 4.2.25 on 2025-11-09 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-is_accepted', '-is_correct', '-likes_count', 'created_at'], 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='answerlike',
            options={'verbose_name': 'Лайк ответа', 'verbose_name_plural': 'Лайки ответов'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='questionlike',
            options={'verbose_name': 'Лайк вопроса', 'verbose_name_plural': 'Лайки вопроса'},
        ),
        migrations.AlterModelOptions(
            name='questiontag',
            options={'verbose_name': 'Тег Вопроса', 'verbose_name_plural': 'Теги Вопросов'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
