# Generated by Django 4.2.25 on 2025-11-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_answer_options_alter_answerlike_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='likes_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='usage_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question', '-created_at'], name='idx_question_answers'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['-is_accepted', '-created_at'], name='idx_accepted_answers'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['-likes_count', 'created_at'], name='idx_popular_answers'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['author', '-created_at'], name='idx_user_answers'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-created_at'], name='idx_created_at_desc'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-likes_count', '-created_at'], name='idx_hot_questions'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-answers_count', '-created_at'], name='idx_popular_questions'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['author', '-created_at'], name='idx_user_questions'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['-usage_count'], name='idx_popular_tags'),
        ),
    ]
