# Generated by Django 4.2.25 on 2025-12-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_answer_created_at_alter_answer_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
    ]
