# Generated by Django 4.2.25 on 2025-12-01 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_old_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionTag',
        ),
    ]
