# Generated by Django 4.2.25 on 2025-12-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_delete_questiontag'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(
                blank=True,
                related_name='questions',
                to='polls.Tag'
            ),
        ),
    ]
